#!/bin/bash
#!/bin/sh

#                     @Arg[0]
SCRIPT=$(readlink -f "$0") # get the path of the script
SCRIPTPATH=$(dirname "$SCRIPT") # get the directory of the script

cd $SCRIPTPATH # change to the directory of the script
echo "Running from $SCRIPTPATH"

function release ($version) {
    echo "Releasing $version"
    # go to root
    cd $SCRIPTPATH/..;

    git add -A
    git commit -m "Release $version $SCRIPT"
    git tag -a $version -m "Release $version $SCRIPT"
    git push origin master --tags

    return ${?};
}

function build ($version) {
    echo "Building $version";
    cd $SCRIPTPATH/;
    pyinstaller.exe --onefile \
    --icon="../icon.ico" \
    ./$SCRIPT && echo "Build complete" || echo "Build failed";
    return
}

if [ $# -eq 0 ]; then
    echo "No arguments supplied";
    exit 1;
fi

if [ $1 == "release" ]; then
    if [ $# -eq 2 ]; then
        release $2;
    else
        echo "No version supplied";
        exit 1;
    fi
elif [ $1 == "build" ]; then
    if [ $# -eq 2 ]; then
        build $2;
    else
        echo "No version supplied";
        exit 1;
    fi
else
    echo "Invalid argument";
    exit 1;
fi